// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-sites.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-sites.ts
var list_sites_default = defineTool({
  name: "list_sites",
  title: "List sites",
  description: "List coffee farm sites (and their blocks) for the signed-in user's organization.",
  inputSchema: { limit: z.number().int().optional().describe("Max sites to return (default 50).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sites").select("id, name, location, created_at, blocks(id, name)").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { sites: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-beds.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var list_beds_default = defineTool2({
  name: "list_beds",
  title: "List drying beds",
  description: "List drying beds with status, dimensions and current assignments.",
  inputSchema: {
    status: z2.string().optional().describe("Optional bed status filter, e.g. empty, occupied, maintenance."),
    limit: z2.number().int().optional().describe("Max beds to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("beds").select("id, bed_number, status, length, width, surface_area, material_type, block_id").order("bed_number").limit(Math.min(Math.max(limit ?? 100, 1), 300));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { beds: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-lots.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_lots_default = defineTool3({
  name: "list_lots",
  title: "List coffee lots",
  description: "List coffee lots with intake date, region, weights and processing status.",
  inputSchema: {
    status: z3.string().optional().describe("Optional lot status filter."),
    limit: z3.number().int().optional().describe("Max lots to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("lots").select("id, lot_number, region, status, initial_weight, current_weight, intake_date").order("intake_date", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { lots: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-inventory.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_inventory_default = defineTool4({
  name: "list_inventory",
  title: "List inventory & machinery",
  description: "List inventory items and machinery with quantity, location and service status.",
  inputSchema: {
    category: z4.string().optional().describe("Optional inventory category filter."),
    limit: z4.number().int().optional().describe("Max items to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("inventory_items").select("id, name, category, quantity, unit, location, status, last_service_date").order("name").limit(Math.min(Math.max(limit ?? 100, 1), 300));
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { items: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-workers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var list_workers_default = defineTool5({
  name: "list_workers",
  title: "List workers",
  description: "List farm workers with role, status and wage information.",
  inputSchema: {
    status: z5.string().optional().describe("Optional worker status filter, e.g. active."),
    limit: z5.number().int().optional().describe("Max workers to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("workers").select("id, name, role, status, wage_rate, wage_type").order("name").limit(Math.min(Math.max(limit ?? 100, 1), 300));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { workers: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-shipments.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z6 } from "npm:zod@^3.25.76";
var list_shipments_default = defineTool6({
  name: "list_shipments",
  title: "List shipments",
  description: "List outgoing coffee shipments with destination, weight and status.",
  inputSchema: {
    status: z6.string().optional().describe("Optional shipment status filter."),
    limit: z6.number().int().optional().describe("Max shipments to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("shipments").select("id, destination, weight, status, shipment_date, confirmed_at, lot_id").order("shipment_date", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { shipments: data ?? [] } };
  }
});

// src/lib/mcp/tools/farm-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.3";
var farm_summary_default = defineTool7({
  name: "farm_summary",
  title: "Farm summary",
  description: "Overview counts of lots, beds, workers, shipments and grinding batches for the organization.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const tables = ["lots", "beds", "workers", "shipments", "grinding_batches"];
    const summary = {};
    for (const table of tables) {
      const { count, error } = await supabase.from(table).select("id", { count: "exact", head: true });
      summary[table] = error ? `error: ${error.message}` : count ?? 0;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "upudfxmpidxjsidfdwyr";
var mcp_default = defineMcp({
  name: "coffee-harvest-hub",
  title: "Coffee Harvest Hub",
  version: "0.1.0",
  instructions: "Tools for Coffee Harvest Hub, a coffee farm post-harvest operations app. Read sites, drying beds, coffee lots, inventory and machinery, workers, shipments, and an overall farm summary. All data is scoped to the signed-in user's organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [farm_summary_default, list_sites_default, list_beds_default, list_lots_default, list_inventory_default, list_workers_default, list_shipments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
